[package]
name = "fsh"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.13"
users = "0.11"
ansi_term = "0.12"
gethostname = "0.2.3"
